{{- if not .Values.persistence.data.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "inception.persistence.pvc.name" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
