{{- if  and (.Values.auth.oauth2.enabled) (.Values.auth.oauth2.clientSecret.value) }}
kind: Secret
metadata:
  name: {{ include "inception.secret.oauth2.name" . }}
type: Opaque
apiVersion: v1
data:
  clientID: {{ required "You must specify an OIDC client ID in the 'auth.oauth2.clientID.value' key of your values file if you're not refering to an existing Secret!" .Values.auth.oauth2.clientID.value | b64enc | quote }}
  clientSecret: {{ required "You must specify an OIDC client secret in the 'auth.oauth2.clientSecret.value' key of your values file if you're not refering to an existing Secret!" .Values.auth.oauth2.clientSecret.value | b64enc | quote }}
{{- end }}